  new Vue({
    el: '#vue',
    data: {
      rateClasses: {
        rateClass: '',
        i310: 'Up to 100 cc',
        i311: '111 - 400 cc',
        i312: '401 - 750 cc',
        i313: '751 - 1150 cc',
        i314: 'Over 1150 cc',
        e311: 'Zero electric',
      },
      territories: {
        territory: '',
        D: 'Lower Mainland',
        E: 'Maple Ridge / Pitt Meadows',
        F: 'Squamish / Whistler area',
        G: 'Pemberton area / Hope area',
        H: 'Fraser Valley',
        L: 'Thompson / Okanagan area',
        N: 'Kootenays',
        P: 'Cariboo area',
        R: 'Prince George area',
        S: 'Northern coast',
        V: 'Peace River area',
        W: 'South Vancouver Island / other islands',
        X: 'Mid Vancouver Island / Sunshine Coast',
        Y: 'Northern Vancouver Island',
        Z: "Other provinces / 'Murrica",
      },
      claimRates: {
        claimRate: '',
        r305: '205% surcharge',
        r265: '165% surcharge',
        r230: '130% surcharge',
        r200: '100% surcharge',
        r175: '75% surcharge',
        r155: '55% surcharge',
        r140: '40% surcharge',
        r130: '30% surcharge',
        r120: '20% surcharge',
        r110: '10% surcharge',
        r100: 'Base Rate',
        r095: '5% discount',
        r090: '10% discount',
        r085: '15% discount',
        r080: '20% discount',
        r075: '25% discount',
        r070: '30% discount',
        r065: '35% discount',
        r060: '40% discount',
        r057: '43% discount',
      }
    },
  })